version: '2'
services:
  redis_master:
    build: ./redis/redis-master/.
    image: redis-master
    ports:
      - "127.0.0.1:6379:6379"

  redis_sentinel:
    build: ./redis/redis-sentinel/.
    image: redis-sentinel
    environment:
      - MASTER_NAME=master01
      - QUORUM=1
      - MASTER=127.0.0.1:6379
      - ANNOUNCE_IP=127.0.0.1
      - ANNOUNCE_PORT=26379
    depends_on:
      - redis_master
    ports:
      - "127.0.0.1:26379:26379"

  mysql:
    build: ./mysql/.
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - "127.0.0.1:3307:3306"

  rocketmq:
    build: ./rocketmq/.
    image: rocketmq
    network_mode: "none"
    ports:
      - "127.0.0.1:9876:9876"

  nginx:
    build: ./nginx/.
    image: nginx
    ports:
      - "127.0.0.1:8088:8088"

  jenkins:
    build: ./jenkins/.
    image: jenkins
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:50000:50000"
